package com.atencion.medica.enums;

public enum EspecialidadMedico {
    MEDICINA_GENERAL, INMUNOLOGIA, CARDIOLOGIA, CIRUGIA, DERMATOLOGIA, ENDOCRINOLOGIA,
    FISIATRIA, GASTROENTEROLOGIA, GIENCOLOGIA, RADIOLOGIA, NUTRIOLOGIA, OFTALMOLOGIA,
    TRAUMATOLOGIA, PEDIATRIA, PSICOLOGIA
}
